//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using System.Runtime.Remoting.Contexts;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.ConditionalAppearance;

namespace TestXafDemo.Module.BusinessObjects.XafAspDemo
{
    [NavigationItem("Countries")]


    public partial class Countries : XPLiteObject
    {
        int fCountryID;
        [Key(true)]
        [Appearance("single",Visibility = ViewItemVisibility.Hide,Context = "DetailView")]

        public int CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<int>(nameof(CountryID), ref fCountryID, value); }
        }
        string fCountryName;
        [Size(50)]
        public string CountryName
        {
            get { return fCountryName; }
            set { SetPropertyValue<string>(nameof(CountryName), ref fCountryName, value); }
        }
        bool fActive;
        [ColumnDbDefaultValue("((1))")]
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
        public Countries()
        {
            fActive = true;
        }
    }

}
